// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWF6oSTMPbNMMyuI0arSpwcf8RV20KQlo',
    appId: '1:297728338814:web:ca26721a093afbb6d2612f',
    messagingSenderId: '297728338814',
    projectId: 'recetas-deliciosas-ee2f8',
    authDomain: 'recetas-deliciosas-ee2f8.firebaseapp.com',
    storageBucket: 'recetas-deliciosas-ee2f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC63T0rVaW0awu9N4yti4eeGFt78wxo1q0',
    appId: '1:297728338814:android:48ee3a8a06ee3109d2612f',
    messagingSenderId: '297728338814',
    projectId: 'recetas-deliciosas-ee2f8',
    storageBucket: 'recetas-deliciosas-ee2f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBynz9hNaDsOrmVswfrM3WXTHIyl-4FI8',
    appId: '1:297728338814:ios:dca89a0a9715e6cbd2612f',
    messagingSenderId: '297728338814',
    projectId: 'recetas-deliciosas-ee2f8',
    storageBucket: 'recetas-deliciosas-ee2f8.appspot.com',
    iosBundleId: 'com.example.recipeFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBynz9hNaDsOrmVswfrM3WXTHIyl-4FI8',
    appId: '1:297728338814:ios:dca89a0a9715e6cbd2612f',
    messagingSenderId: '297728338814',
    projectId: 'recetas-deliciosas-ee2f8',
    storageBucket: 'recetas-deliciosas-ee2f8.appspot.com',
    iosBundleId: 'com.example.recipeFood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWF6oSTMPbNMMyuI0arSpwcf8RV20KQlo',
    appId: '1:297728338814:web:d9b1476ff63c7d84d2612f',
    messagingSenderId: '297728338814',
    projectId: 'recetas-deliciosas-ee2f8',
    authDomain: 'recetas-deliciosas-ee2f8.firebaseapp.com',
    storageBucket: 'recetas-deliciosas-ee2f8.appspot.com',
  );
}
